### ISSUE TITLE
Unable to install (MacOS 10.12.2 -- unused 0.6.1.0)

### ISSUE THREAD

**Issue by kevinjalbert** [joshuaclayton/homebrew-formulae#3]
Homebrew 1.1.6
Homebrew/homebrew-core (git revision 0a6c; last commit 2017-01-03)

MacOS 10.12.2

----

When trying to install I get the following:

```
==> cabal install --jobs=8 --max-backjumps=100000 --prefix=/usr/local/Cellar/unused/0.6.1.0
Last 15 lines from /Users/jalbert/Library/Logs/Homebrew/unused/04.cabal:
[ 6 of 45] Compiling Unused.TermSearch.Types ( src/Unused/TermSearch/Types.hs, dist/dist-sandbox-5657ef82/build/Unused/TermSearch/Types.o )
[ 7 of 45] Compiling Unused.TermSearch ( src/Unused/TermSearch.hs, dist/dist-sandbox-5657ef82/build/Unused/TermSearch.o )
[ 8 of 45] Compiling Unused.Projection.Transform ( src/Unused/Projection/Transform.hs, dist/dist-sandbox-5657ef82/build/Unused/Projection/Transform.o )

src/Unused/Projection/Transform.hs:10:1: error:
    Failed to load interface for ‘Text.Inflections.Parse.Types’
    Perhaps you meant
      Text.Inflections.Types
      Text.Inflections.Parse.CamelCase
      Text.Inflections.Parse.SnakeCase
    Use -v to see a list of the files searched for.
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
unused-0.6.1.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by eugeneius** [comment]
This is happening because the inflections library changed its API significantly in v0.3.0.0: https://github.com/stackbuilders/inflections-hs/commit/212d0cb3e70e5f8ccdf041e2e231b0492555b76a

[Installing with Stack](https://github.com/joshuaclayton/unused#installing-by-hand) still works, since it uses an LTS release that doesn't contain the new version.

**Comment by eugeneius** [comment]
It looks like unused v0.7.0.0 fixed this: https://github.com/joshuaclayton/unused/commit/8a16494a649f8c7c82e42e21a8fa30925f9282d3

**Comment by glaucocustodio** [comment]
Please, help me, I can't get unused installed..

## Brew

$ brew install unused

==> Installing unused from joshuaclayton/formulae
==> Downloading https://github.com/joshuaclayton/unused/archive/v0.8.0.0.tar.gz
Already downloaded: /Users/glauco/Library/Caches/Homebrew/unused-0.8.0.0.tar.gz
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=4 --max-backjumps=100000 --only-dependencies
Last 15 lines from /Users/glauco/Library/Logs/Homebrew/unused/03.cabal:
base>=4.5 && <4.11)
[__4] rejecting: base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0,
base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: primitive, vector, base, cassava,
unused
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/joshuaclayton/homebrew-formulae/issues

These open issues may also help:
Unable to install (MacOS 10.12.2 -- unused 0.6.1.0) https://github.com/joshuaclayton/homebrew-formulae/issues/3


## Stack

$ stack install unused

Populated index cache.

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for unused-0.8.0.0:
    cassava-0.5.1.0 from stack configuration does not match >=0.4.5.0 && <0.5  (latest matching version is 0.4.5.1)
    inflections-0.4.0.3 from stack configuration does not match >=0.3.0.0 && <0.4  (latest matching version is 0.3.0.0)
    megaparsec-6.4.1 from stack configuration does not match >=5.1.2 && <6  (latest matching version is 5.3.1)
needed since unused is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be
    convenient when dealing with many complicated constraint errors, but results may be unpredictable.

  * Recommended action: try adding the following to your extra-deps in /Users/glauco/.stack/global-project/stack.yaml:

- cassava-0.4.5.1
- inflections-0.3.0.0
- megaparsec-5.3.1

Plan construction failed.

cat ~/.stack/global-project/stack.yaml

packages: []
resolver: lts-11.13

**Comment by sekmo** [comment]
Any news from the front?

**Comment by joshuaclayton** [comment]
@sekmo @glaucocustodio @eugeneius @kevinjalbert sorry for the delay - I've bumped a version on Homebrew that should install correctly. Mind giving it another go?

**Comment by kevinjalbert** [comment]
@joshuaclayton It has been a while since I've tried to get `unused` working. I gave it another go and I'm hitting a different issue (which could just be the way my system's state is now?).

```
❯ brew install unused
==> Installing unused from joshuaclayton/formulae
Error: No available formula with the name "ag" (dependency of joshuaclayton/formulae/unused)
```

Looks like the `ag` formula doesn't actually exist, and it is called `the_silver_searcher`. Maybe that changed recently? Or something else?

**Comment by joshuaclayton** [comment]
@kevinjalbert hmm; with their aliasing, it should work (I've confirmed locally by uninstalling `ag` and `brew reinstall unused`. Mind running `brew update` and giving it another whirl?

**Comment by kevinjalbert** [comment]
Still hitting the issue:

![](https://api.monosnap.com/rpc/file/download?id=vBB6eYcGJfRawDlb9NWqeyKAJx2emo)

I forgot I had `ag` aliases so I got rid of that, then I uninstall `the_silver_searcher` so that `ag` was nothing.

```
> brew --version
Homebrew 1.7.3-102-g88e69f5
Homebrew/homebrew-core (git revision 612bdc; last commit 2018-09-11)
Homebrew/homebrew-cask (git revision 8c4d59f; last commit 2018-09-10)
```

I assume I might just be in a bad state eh? Oh well 🤷‍♂️

**Comment by DiscoStarslayer** [comment]
Just tested the above on my system, and it worked as expected. Not sure why the `ag` alias isn't working for @kevinjalbert.

**Comment by miketheman** [comment]
Recommend closing this issue now that the dependencies appear to work for installation.

**Comment by kevinjalbert** [comment]
I tried again and it works as expected. Closing this issue out.
